
from PyQt5 import QtCore, QtGui, QtWidgets
import cv2
face_detector = cv2.CascadeClassifier('cascades/data/haarcascade_frontalface_alt2.xml')
import pyshine
import time
class Ui_AttendenceSystem(object):
    def setupUi(self, AttendenceSystem):
        AttendenceSystem.setObjectName("AttendenceSystem")
        AttendenceSystem.setFixedSize(1280, 720)
        self.horizontalLayoutWidget = QtWidgets.QWidget(AttendenceSystem)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 30, 1111, 681))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblCam = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblCam.setEnabled(True)
        self.lblCam.setFrameShape(QtWidgets.QFrame.Box)
        self.lblCam.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblCam.setLineWidth(2)
        self.lblCam.setMidLineWidth(0)
        self.lblCam.setText("")
        self.lblCam.setTextFormat(QtCore.Qt.AutoText)
        self.lblCam.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCam.setObjectName("lblCam")
        self.horizontalLayout_2.addWidget(self.lblCam)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btnCam = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnCam.setFont(font)
        self.btnCam.setObjectName("btnCam")
        self.verticalLayout_6.addWidget(self.btnCam)
        self.btnCapture = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnCapture.setFont(font)
        self.btnCapture.setObjectName("btnCapture")
        self.verticalLayout_6.addWidget(self.btnCapture)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_3.setStretch(0, 7)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 8)
        self.verticalLayout.setStretch(1, 2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(120, 0, 81, 10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblCap = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblCap.setFrameShape(QtWidgets.QFrame.Box)
        self.lblCap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblCap.setLineWidth(4)
        self.lblCap.setText("")
        self.lblCap.setTextFormat(QtCore.Qt.RichText)
        self.lblCap.setObjectName("lblCap")
        self.horizontalLayout_5.addWidget(self.lblCap)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(25, 21, 13, 0)
        self.formLayout.setHorizontalSpacing(14)
        self.formLayout.setVerticalSpacing(46)
        self.formLayout.setObjectName("formLayout")
        self.lblId = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblId.sizePolicy().hasHeightForWidth())
        self.lblId.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblId.setFont(font)
        self.lblId.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblId.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblId.setObjectName("lblId")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblId)
        self.txtId = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtId.sizePolicy().hasHeightForWidth())
        self.txtId.setSizePolicy(sizePolicy)
        self.txtId.setObjectName("txtId")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtId)
        self.lblName = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblName.setFont(font)
        self.lblName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblName.setObjectName("lblName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblName)
        self.txtName = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtName.sizePolicy().hasHeightForWidth())
        self.txtName.setSizePolicy(sizePolicy)
        self.txtName.setObjectName("txtName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtName)
        self.lblDob = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblDob.setFont(font)
        self.lblDob.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDob.setObjectName("lblDob")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblDob)
        self.txtDob = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget)
        self.txtDob.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDob.sizePolicy().hasHeightForWidth())
        self.txtDob.setSizePolicy(sizePolicy)
        self.txtDob.setTime(QtCore.QTime(0, 0, 0))
        self.txtDob.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.txtDob.setCalendarPopup(True)
        self.txtDob.setTimeSpec(QtCore.Qt.LocalTime)
        self.txtDob.setObjectName("txtDob")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtDob)
        self.lblAge = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblAge.setFont(font)
        self.lblAge.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAge.setObjectName("lblAge")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblAge)
        self.txtAge = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.txtAge.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAge.sizePolicy().hasHeightForWidth())
        self.txtAge.setSizePolicy(sizePolicy)
        self.txtAge.setObjectName("txtAge")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtAge)
        self.lblPhone = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblPhone.setFont(font)
        self.lblPhone.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPhone.setObjectName("lblPhone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblPhone)
        self.txtPhone = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPhone.sizePolicy().hasHeightForWidth())
        self.txtPhone.setSizePolicy(sizePolicy)
        self.txtPhone.setObjectName("txtPhone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtPhone)
        self.lblAddress = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblAddress.setFont(font)
        self.lblAddress.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAddress.setObjectName("lblAddress")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblAddress)
        self.txtAddress = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAddress.sizePolicy().hasHeightForWidth())
        self.txtAddress.setSizePolicy(sizePolicy)
        self.txtAddress.setObjectName("txtAddress")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtAddress)
        self.verticalLayout_7.addLayout(self.formLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.btnSave = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSave.sizePolicy().hasHeightForWidth())
        self.btnSave.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnSave.setFont(font)
        self.btnSave.setIconSize(QtCore.QSize(16, 16))
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_8.addWidget(self.btnSave)
        self.btnResetTxt = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResetTxt.sizePolicy().hasHeightForWidth())
        self.btnResetTxt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnResetTxt.setFont(font)
        self.btnResetTxt.setObjectName("btnResetTxt")
        self.horizontalLayout_8.addWidget(self.btnResetTxt)
        self.btnExit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit.sizePolicy().hasHeightForWidth())
        self.btnExit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_8.addWidget(self.btnExit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout_2.setStretch(2, 3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 7)
        self.horizontalLayout.setStretch(1, 3)

        self.btnExit.clicked.connect(self.Exit)
        self.btnCam.clicked.connect(self.OpenCam)
        self.btnCapture.clicked.connect(self.cutFace)

        self.retranslateUi(AttendenceSystem)
        QtCore.QMetaObject.connectSlotsByName(AttendenceSystem)

    def OpenCam(self):
        cam = True
        if cam:
            self.vid = cv2.VideoCapture(0)
        else:
            self.vid = cv2.VideoCapture("memetotally.mp4")

        count = 0
        while True:
            OK, self.frame = self.vid.read()
            gray = cv2.cvtColor(self.frame, cv2.COLOR_BGR2GRAY)
            faces = face_detector.detectMultiScale(gray, scaleFactor=1.5, minNeighbors=5)
            # time.sleep(0.5)
            for (x, y, w, h) in faces:
                color = (0, 255, 0)
                stroke = 2
                end_cord_x = x + w
                end_cord_y = y + h
                roi = self.cuttedFace= self.frame[y+2: y+h-2, x+2:x+w-2]
                cv2.imwrite('imgs_face/roi_{}.jpg'.format(count),roi)
                cv2.rectangle(self.frame, (x, y), (end_cord_x, end_cord_y), color, stroke)
                count += 1
            self.update()
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break


    def cutFace(self):

        image = cv2.cvtColor(self.cuttedFace, cv2.COLOR_BGR2RGB)
        image = cv2.resize(image, (128, 126))
        img = QtGui.QImage(image, image.shape[1], image.shape[0], image.strides[0], QtGui.QImage.Format_RGB888)

        self.lblCap.setPixmap(QtGui.QPixmap.fromImage(img))
    def update(self):
        text= str(time.strftime("%H:%M "))
        image= pyshine.putBText(self.frame,text,text_offset_x=10,text_offset_y=25,vspace=20,hspace=10,
                                font_scale=0.7, text_RGB=(255,0,0))

        self.setPhoto(self.frame)

    def setPhoto(self, image):
        # print(image.shape, image.strides)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = cv2.resize(image, (768, 535))
        img = QtGui.QImage(image, image.shape[1], image.shape[0], image.strides[0], QtGui.QImage.Format_RGB888)

        self.lblCam.setPixmap(QtGui.QPixmap.fromImage(img))

    def Exit(self):
        exit(0)
    def retranslateUi(self, AttendenceSystem):
        _translate = QtCore.QCoreApplication.translate
        AttendenceSystem.setWindowTitle(_translate("AttendenceSystem", "Dialog"))
        self.btnCam.setText(_translate("AttendenceSystem", "Camera"))
        self.btnCapture.setText(_translate("AttendenceSystem", "Capture"))
        self.lblId.setText(_translate("AttendenceSystem", "ID"))
        self.lblName.setText(_translate("AttendenceSystem", "Name"))
        self.lblDob.setText(_translate("AttendenceSystem", "Dob"))
        self.txtDob.setDisplayFormat(_translate("AttendenceSystem", "dd/MM/yyyy"))
        self.lblAge.setText(_translate("AttendenceSystem", "Age"))
        self.lblPhone.setText(_translate("AttendenceSystem", "Phone"))
        self.lblAddress.setText(_translate("AttendenceSystem", "Address"))
        self.btnSave.setText(_translate("AttendenceSystem", "Save"))
        self.btnResetTxt.setText(_translate("AttendenceSystem", "Reset"))
        self.btnExit.setText(_translate("AttendenceSystem", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AttendenceSystem = QtWidgets.QDialog()
    ui = Ui_AttendenceSystem()
    ui.setupUi(AttendenceSystem)
    AttendenceSystem.show()
    sys.exit(app.exec_())

